apps/salesforce-app/force-app/main/default/objects/ChatMessage__c/ChatMessage__c.object-meta.xml
<CustomObject>
    <label>Chat Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

apps/salesforce-app/force-app/main/default/objects/ChatMessage__c/fields/Chat_Conversation__c.field-meta.xml
<CustomField>
    <fullName>Chat_Conversation__c</fullName>
    <label>Chat Conversation</label>
    <referenceTo>ChatConversation__c</referenceTo>
    <relationshipLabel>Chat Messages</relationshipLabel>
    <relationshipName>Chat_Conversation_Messages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

apps/salesforce-app/force-app/main/default/objects/ChatMessage__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sender</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Chat_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

apps/salesforce-app/force-app/main/default/objects/ChatMessage__c/fields/Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Name__c</fullName>
    <label>Sender Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

apps/salesforce-tightknit/force-app/main/default/objects/ChatMessage__c/fields/Sender_Photo_URL__c.field-meta.xml
<CustomField>
    <fullName>Sender_Photo_URL__c</fullName>
    <label>Sender Photo URL</label>
    <type>Url</type>
</CustomField>

apps/salesforce-app/force-app/main/default/objects/ChatMessage__c/fields/Sent_At__c.field-meta.xml
<CustomField>
    <fullName>Sent_At__c</fullName>
    <label>Sent At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

apps/salesforce-app/force-app/main/default/classes/ChatController.cls
/**
 * Retrieves all chat messages (ChatMessage__c) for a given chat conversation (chatConversationId).
 * @param chatConversationId - The chat conversation ID.
 * @return A list of chat messages for the given chat conversation ID.
 */
public with sharing class ChatController {
    @AuraEnabled(cacheable=true)
    public static List<ChatMessage__c> getChatMessages(String chatConversationId) {
        return [SELECT Id, Body__c, Sender_Name__c, Sender__c, Sender_Photo_URL__c, Sent_At__c, Chat_Conversation__c FROM ChatMessage__c WHERE Chat_Conversation__c = :chatConversationId];
    }
}